apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: udp-client
  template:
    metadata:
      labels:
        name: udp-client 
    spec:
      containers:
      - name: udp-client
        image: ghcr.io/tom1299/k8s-udp-load-balancing/udp-client:latest
        imagePullPolicy: Always
        env:
        - name: SERVER_ADDRESS
          value: "$(UDP_NGINX_SERVICE_SERVICE_HOST)"
        - name: SERVER_PORT
          value: "$(UDP_NGINX_SERVICE_SERVICE_PORT)"
      imagePullSecrets:
      - name: regcred
