---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-nginx-deployment
  labels:
    app: udp-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-nginx
  template:
    metadata:
      labels:
        app: udp-nginx
    spec:
      hostAliases:
      - ip: "10.96.0.10"
        hostnames:
        - "dns-server"
      containers:
      - name: udp-nginx
        image: ghcr.io/tom1299/k8s-udp-load-balancing/udp-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5353
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: udp-nginx-service
  labels:
    app: udp-nginx-service
spec:
  ports:
  - port: 5353
    protocol: UDP
    targetPort: 5353
  selector:
    app: udp-nginx