apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-server-deployment
  labels:
    app: udp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udp-server
  template:
    metadata:
      labels:
        app: udp-server
    spec:
      containers:
      - name: udp-server
        image: docker.pkg.github.com/tom1299/k8s-udp-load-balancing/udp-server
        imagePullPolicy: Always
        ports:
        - containerPort: 10002
          protocol: UDP
        readinessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          failureThreshold: 30
          periodSeconds: 10
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: udp-server-service-headless
spec:
  clusterIP: None
  ports:
    - name: udp
      port: 10002
      protocol: UDP
  selector:
    app: udp-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: udp-server-service
spec:
  type: LoadBalancer
  ports:
  - port: 10002
    protocol: UDP
  selector:
    app: udp-server