name: ci

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push udp-client
        uses: docker/build-push-action@v2
        with:
          context: ./k8s-udp-client
          file: ./k8s-udp-client/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ghcr.io/tom1299/k8s-udp-load-balancing/udp-client:latest
      -
        name: Build and push udp-server
        uses: docker/build-push-action@v2
        with:
          context: ./k8s-udp-server
          file: ./k8s-udp-server/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ghcr.io/tom1299/k8s-udp-load-balancing/udp-server:latest
      -
        name: Build and push udp-nginx
        uses: docker/build-push-action@v2
        with:
          context: ./k8s-udp-nginx
          file: ./k8s-udp-nginx/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ghcr.io/tom1299/k8s-udp-load-balancing/udp-nginx:latest
